---
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.21.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.20.0
    hooks:
      - id: yamllint
