---
- id: shellcheck
  name: Test shell scripts with shellcheck
  description: Shell scripts conform to shellcheck
  entry: shellcheck
  language: system
  types: [shell]
  args: [-e, SC1091]
