---
exclude: ^.github/pull_request_template.md$

repos:
  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: hooks/yamllint.py
        language: python
        types: [file, yaml]
        args: [--encoding, UTF-8]
        additional_dependencies: [yamllint]

  - repo: local
    hooks:
      - id: pretty-quick
        name: pretty-quick
        entry: pretty-quick
        language: node
        types: [text]
        args: [--staged]
        require_serial: true
        additional_dependencies: [prettier, pretty-quick]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/PyCQA/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint-system
