---
repos:
  - repo: local
    hooks:
      - id: pretty-quick
        name: pretty-quick
        entry: pretty-quick
        language: node
        types: [text]
        args: [--staged]
        require_serial: true
        additional_dependencies: [prettier, pretty-quick]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.21.0
    hooks:
      - id: markdownlint

  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: hooks/yamllint.py
        language: python
        types: [file, yaml]
        args: [--encoding, UTF-8]
        additional_dependencies: [yamllint]
